apiVersion: apps/v1
kind: Deployment
metadata:
  name: ninelush-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ninelush-auth
  template:
    metadata:
      labels:
        app: ninelush-auth
    spec:
      containers:
        - name: ninelush-auth
          image: docker.io/chillabit2332/ninelush-auth
          env: 
            - name: MONGO_URI
              value: 'mongodb://ninelush-auth-mongo-srv:27017/ninelush-auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ninelush-auth-srv
spec:
  selector:
    app: ninelush-auth
  ports:
    - name: ninelush-auth
      protocol: TCP
      port: 3000
      targetPort: 3000
