apiVersion: apps/v1
kind: Deployment
metadata:
  name: ninelush-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ninelush-client
  template:
    metadata:
      labels:
        app: ninelush-client
    spec:
      containers:
        - name: ninelush-client
          image: docker.io/chillabit2332/ninelush-client
---
apiVersion: v1
kind: Service
metadata:
  name: ninelush-client-srv
spec:
  selector:
    app: ninelush-client
  ports:
    - name: ninelush-client
      protocol: TCP
      port: 3000
      targetPort: 3000
